# 제너레이터, async/await

## 제너레이터

제네레이터는 코드 블록의 실행을 일시 중지했다가 필요한 시점에 재개할 수 있는 특수한 함수

**제너레이터와 일반 함수의 차이**
1. 제너레이터 함수는 함수 호출자에게 함수 실행의 제어권을 양도할 수 있다.

2. 제너레이터 함수는 함수 호출자와 함수의 상태를 주고받을 수 있다.

3. 제너레이터 함수를 호출하면 제너레이터 객체를 반환한다.

## 제너레이터 함수 사용법

제너레이터 함수는 function* 키워드로 선언하고 하나 이상의 yield 표현식을 포함한다.

```js
// 선언문
function* gene1() {
  yield 1;
}

// 함수 표현식
const gene2 = function* () {
  yield 1;
};

// 제너레이터 메서드
const obj = {
  * gene3() {
    yield 1;
  }
};

// 클래스 메서드
class Obj {
  * gene4() {
    yield 1;
  }
}
```

`*` 의 위치는 function 키워드와 함수 이름 사이라면 어디든 상관없지만 일부러 사용할때마다 위치를 다르게 할 필요는 없을것같다.

제너레이터 함수는 화살표 함수로 정의할 수 없다.

제너레이터 함수는 new 연산자와 함께 생성자 함수로 호출할 수 없다. (non-constructor)

## 제너레이터 객체

제너레이터 함수는 일반함수와 다르게 제너레이터 객체를 생성해 반환한다. 그 제너레이터 객체는 이터러블(iterable)이면서 동시에 이터레이터(iterator)이다.

제너레티어 객체는 next, return, throw 메서드를 갖는다.

- next 메서드
  - 제너레이터 함수의 yield 표현식까지 코드 블록을 실행하고 이터레이터 객체를 반환한다.
  - value 프로퍼티 값: yield된 값
  - done 프로퍼티 값: false;

- return 메서드
  - 마찬가지로 이터레이터 객체를 반환한다.
  - value 프로퍼티 값: return 메서드를 호출할때 인수로 전달받은 값
  - done 프로퍼티 값: true;

- throw 메서드
  - 이터레이터 객체를 반환한다.
  - throw메서드를 호출할때 인수로 전달받은 에러를 발생시킴
  - value 프로퍼티 값: undefined
  - done 프로퍼티 값: true;

## 제너레이터의 일시 중지와 재개

제너레이터는 yield 키워드와 next 메서드를 통해 실행을 일시 중지했다가 필요한 시점에 재개할 수 있다.

제너레이터 객체의 next 메서드를 호출하면 제너레이터 함수의 코드 블록을 실행한다.(yield 표현식까지만)

이때 yield 키워드는 제너레이터 함수의 실행을 일시 중지 시키거나 yield 키워드 뒤에 오는 표현식의 평가 결과를 제너레이터 함수 호출자에게 반환한다.

제너레이터 객체의 next 메서드에 전달한 인수는 제너레이터 함수의 yield 표현식을 할당받는 변수에 할당된다.
말 그대로 yield 표현식의 평가결과가 아닌 next 메서드의 인수값이 할당되는것이다.

일반적으로 제너레이터의 반환값은 의미가 없다.(return을 종료의 의미로만 사용)


## async/await

### async 함수

ES8에서 제너레이터보다 간단하고 가독성 좋게 비동기 처리를 동기 처리처럼 동작하도록 구현할 수 있는 async/await가 도입되었다.

async/await는 프로미스를 기반으로 동작한다. async/await를 사용하면 프로미스의 then, catch, finally 후속 처리 메서드에 콜백 함수를 전달하며 비동기 처리 결과를 처리할 필요없이 동기 처리처럼 프로미스를 사용할 수 있다.

## await 키워드

await 키워드는 프로미스가 settled 상태(비동기 처리가 수행된 상태)가 될 때까지 대기하다가 settled 상태가 되면 프로미스가 resolve한 처리 결과를 반환한다. (await 키워드는 반드시 프로미스 앞에서 사용해야함)

### 에러처리

비동기 처리를 위한 콜백 패턴의 단점은 에러 처리가 곤란하다는 것이다. 에러는 호출자 방향으로 전파된다. 하지만 비동기 함수의 콜백 함수를 호출한 것은 비동기 함수가 아니기때문에 try/catch 문을 사용해 에러를 캐치할 수 없다.

하지만 async/await에서 에러 처리는 try/catch문을 사용할 수 있다. 콜백 함수를 인수로 전달받는 비동기 함수와는 달리 프로미스를 반환하는 비동기 함수는 명시적으로 호출할 수 있기 때문에 호출자가 명확하다.

<cite>위 내용은 poiemaweb.com 페이지를 참조, 정리하여 작성하였습니다.</cite>